bi_fdw_csv_path: /home/syh/csv

bi_inventory: bi-show-your-heart-inventory
bi_user: bi
bi_user_group: bi
bi_python_version: "3.8.10"
bi_venv_name: bi

bi_fdw_url: https://github.com/EnterpriseDB/mysql_fdw.git
bi_fdw_path: "/home/{{ bi_user }}/fdw"
bi_postgresql_reader_user: reader
bi_postgresql_dbt_user: dbt


bi_dwh_database: dwh
bi_dwh_database_extensions:
  - postgres_fdw
  - mysql_fdw
  - file_fdw
bi_dwh_external_schema: external

bi_superset_git_url: https://github.com/apache/superset.git
bi_superset_git_version: 2.0.1
bi_superset_path: "/home/{{ bi_user }}/superset"

bi_dbt_scripts_repo: https://github.com/Show-your-Heart/ShowYourHeart-data-scripts.git
bi_dbt_scripts_dir: "/home/{{ bi_user }}/dbt/dbtscripts"
bi_dbt_version: 1.9.1


bi_airflow_path: "/home/{{ bi_user }}/airflow"
bi_airflow_path_scripts: "/home/{{ bi_user }}/airflow-scripts"
bi_airflow_scripts_repo: https://github.com/Show-your-Heart/ShowYourHeart-data-dags.git
bi_airflow_version: 2.10.5-python3.10


bi_docs_port: 9876
bi_docs_path: "/home/{{ bi_user }}/docs"
bi_docs_scripts_repo: https://git.coopdevs.org/coopdevs/bi/generador-documentacio-superset.git

bi_biallinone_port: 0

superset_docker_version: 3.1.1

airflow_python_libraries:
  - dbt-postgres=={{bi_dbt_version}}
  - pdfkit==1.0.0
  - matplotlib==3.5.3
  - paramiko==2.11.0
  - openpyxl==3.1.1
  - b2sdk==1.23.0
  - libsass==0.23.0
  - setuptools~=75.3.0
  - pandas~=1.5.3
  - Jinja2~=3.1.2
  - pathvalidate~=3.2.1
  - weasyprint~=63.0
  - fuzzywuzzy~=0.18.0
  - pyppeteer~=0.2.6
  - mailjet-rest==1.3.4
  - selenium~=4.26.1
  - wakepy~=0.10.1
  - pngquant~=1.0.8
  - pyyaml==6.0.1
  - standard-imghdr==3.13.0
  - pdfgen~=1.0.5